server:
  port: 8089


client:
  port: 8080
  address: 192.168.0.106

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/movie_share?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #邮箱配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2315447580@qq.com
    password: fadsqocqyecgeabg
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  servlet:
    multipart:
      max-file-size: 2MB


  redis:
    #数据库索引
    database: 0
    host: localhost
    port: 6379
    password:
    #连接超时时间
    timeout: 5000

  mvc:
    dispatch-options-request: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location:  classpath:mybatis/config/mybatis-config.xml

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间/毫秒，6小时  1小时 = 3600000 毫秒
  expiration: 21600000
  # 在线用户key
  online: online-token
  # 验证码
  codeKey: code-key
#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

email-validate:
  key: email-validate
  expiration: 24 #小时

reset-password:
  key: reset-password
  expiration: 1




mail:
  fromMail:
    addr: 2315447580@qq.com
  server:
    address: 192.168.0.106
    port: 8089

video:
  upload:
    tmp:
      dir: D:\upload\tmp
    expire: 24
    root: D:\upload\video\root
    url:
      root: /video/



pic:
  upload:
    root: D:\upload\image
    url:
      root: /image/
#showSql
logging:
  level:
    com:
      hao:
        movieshareback:
          dao: debug

es:
  host: localhost
  port: 9200
  scheme: http

